name: Helix Algolia Sync
on:
  repository_dispatch:
    types:
      - resource-published
      - resources-published
      - resource-unpublished
      - resources-unpublished
jobs:
  update-algolia-index:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Path: ${{ github.event.client_payload.path }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

#      - name: Install dependencies for action
#        run: |
#          cd actions/helix-algolia-sync-ts
#          npm i

      - name: Helix Sync With Algolia Index
        uses: ./actions/helix-algolia-sync-ts
        with:
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          algolia-application-id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          algolia-index-name: ${{ vars.ALGOLIA_INDEX_NAME }}